version: 1
formatters:
  stdout:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"
    datefmt: "%H:%M:%S"
  file:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: stdout
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: file
    filename: logs/ts3bot.log
    maxBytes: 1048576
    backupCount: 4
loggers:
  __main__:
    level: INFO
    handlers: [stdout, file]
    